export const sections = [
  {
    tag: "socials",
    name: "Youtube",
    username: "chomchom4679",
    platform: "youtube",
    landing_page_link: "https://www.youtube.com/",
    profile_link: "https://www.youtube.com/channel/UClC2jFOQmBHF3NXsBNd8QCQ",
  },
  {
    tag: "socials",
    name: "Twitter",
    username: "PichkariDarKo",
    platform: "twitter",
    landing_page_link: "https://twitter.com/home",
    profile_link: "https://twitter.com/PichKariDarKo",
  },
  {
    tag: "norm",
    name: "Gmail",
    username: "chawhannaman5@gmail.com",
    platform: "gmail",
    landing_page_link: "https://mail.google.com/mail/u/0/#inbox",
    profile_link: "https://mail.google.com/mail/u/0/#inbox",
  },
  {
    tag: "study",
    name: "Github",
    username: "namannc13",
    platform: "github",
    landing_page_link: "https://github.com/dashboard",
    profile_link: "https://github.com/namannc13",
  },
  {
    tag: "study",
    name: "LeetCode",
    username: "chomchom13",
    platform: "leetcode",
    landing_page_link: "https://leetcode.com/problemset/",
    profile_link: "https://leetcode.com/chomchom13/",
  },
  {
    tag: "norm",
    name: "Chalkpad",
    username: "NamanChawhan",
    platform: "chalkpad",
    landing_page_link:
      "https://punjab.chitkara.edu.in//Interface/Student/index.php",
    profile_link: "https://punjab.chitkara.edu.in//Interface/Student/index.php",
  },
  {
    tag: "socials",
    name: "Pinterest",
    username: "chomchom13",
    platform: "pinterest",
    landing_page_link: "https://in.pinterest.com/",
    profile_link: "https://in.pinterest.com/chomchom13/",
  },

  {
    tag: "socials",
    name: "Twitch",
    username: "chomchombh",
    platform: "twitch",
    landing_page_link: "https://www.twitch.tv/directory/following",
    profile_link: "https://www.twitch.tv/chomchombh",
  },
  {
    tag: "socials",
    name: "Reddit",
    username: "Quirky_Knowledge_394",
    platform: "reddit",
    landing_page_link: "https://www.reddit.com/",
    profile_link: "https://www.reddit.com/user/Quirky_Knowledge_394/",
  },
  {
    tag: "socials",
    name: "Instagram",
    username: "tru.bhay",
    platform: "instagram",
    landing_page_link: "https://www.instagram.com/",
    profile_link: "https://www.instagram.com/tru.bhay/",
  },
  {
    tag: "anime",
    name: "HiAnime",
    username: "Naman",
    platform: "hianime",
    landing_page_link: "https://hianime.to/home",
    profile_link: "https://hianime.to/user/watch-list",
  },
  {
    tag: "study",
    name: "Neetcode",
    username: "Naman",
    platform: "neetcode",
    landing_page_link: "https://neetcode.io/practice",
    profile_link: "https://neetcode.io/practice",
  },
  {
    tag: "norm",
    name: "Monkeytype",
    username: "Naman",
    platform: "monkeytype",
    landing_page_link: "https://monkeytype.com/",
    profile_link: "https://monkeytype.com/account",
  },
];
